### ISSUE TITLE
[TASK] - Toaster custom stijl verwijderen

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-alert#31]
**Beschrijving**
De vl-ui-alert webcomponent binnen een vl-ui-toaster krijgt opacity transition stijl voor een effect bij het verwijderen van een toast element. Deze stijl kan niet overgenomen worden van webuniversum via SCSS omdat er een shadow DOM tussen de vl-ui-toaster en vl-ui-alert alert componenten zit. Informeren bij Webuniversum of volgende wijziging doorgevoerd mag worden bij vl-ui-toaster:

```css
.vl-toaster {
  position: fixed;
  width: 30rem;
  z-index: z("toaster");
  top: 0;
  right: 0;

  &[class*="left"] {
    right: auto;
    left: 0;
  }

  &[class*="bottom"] {
    top: auto;
    bottom: 0;
  }

  &--fade {
    opacity: 0 !important; // sass-lint:disable-line no-important
  }
}
```

En volgende toevoeging bij vl-ui-alert:

```css
.vl-alert {
  opacity: 1;
  transition: opacity 0.3s;
  margin: 1rem;
   
  &--fade-out {
    opacity: 0;
  }
}
```
